language: node_js

node_js:
  - 11.12.0

services:
  - mongodb

before_install:
  - npm install istanbul -g
  - npm install coveralls -g
  - npm install mocha -g

script:
  - npm test

after_success:
  - npm run coveralls
